function selectFormantFile
global ostFile

list =  [{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_1.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_2.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_3.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_4.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_5.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_6.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_7.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_8.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_9.ost'};...
{'C:\speechres\AudapterStudies\audapter_matlab\example_data\formant_reflex_10.ost'}];

randFind = round(1 + (10-1)*rand(1,1));

ostFile = char(list(randFind));

end